export { ReactComponent as ClearAllIcon } from './icons/clear_all.icon.svg'
export { ReactComponent as EditIcon } from './icons/edit.icon.svg'
export { ReactComponent as CloseIcon } from './icons/close.icon.svg'
export { ReactComponent as SuccessIcon } from './icons/success.icon.svg'
export { ReactComponent as WarningIcon } from './icons/warning.icon.svg'
export { ReactComponent as ErrorIcon } from './icons/error.icon.svg'
export { ReactComponent as HamMenuIcon } from './icons/ham_menu.icon.svg'
export { ReactComponent as SearchIcon } from './icons/search.icon.svg'
export { ReactComponent as SearchUserIcon } from './icons/search_user.icon.svg'
export { ReactComponent as SendIcon } from './icons/send.icon.svg'

export { default as UserDefaultImage } from './images/user.image.png'